### ISSUE TITLE
Unstable fps

### ISSUE THREAD

**Issue by JuZi233** [lovettchris/wincam#1]
I used your test code, and the fps fluctuated significantly. The time taken by get_bgr_frame() fluctuated regularly from 1ms to 17ms. By the way, can WinCam take screenshots of full-screen [applications?](url)

![4c8fe9e60ba4cd8c007a472bedbec016](https://github.com/lovettchris/wincam/assets/28708044/bdd32d41-dd23-4f8a-adb2-58a8d6a3f51a)

**Comment by lovettchris** [comment]
First I would definitely take the print out of the loop - it is probably destabilizing your times a lot.  Save the times to an array and print the min/max/avg after the loop and save them so you can plot them.

Not sure what your full screen is, with my NVidia T1000 GPU (which is not that great) I see these times on a 1920x1080 monitor, with an average 10.5 milliseconds, but yes I see similar fluctuations.  But i've noticed this is dependent on which monitor I use and which GPU.

![image](https://github.com/lovettchris/wincam/assets/18707114/75e955a4-8543-4079-8d5d-766d0f1b9e61)

If I go smaller at 1024 x 576 it is much smoother down around an average of 3.6 milliseconds and this is the kind of size I need to train Neural networks.

![image](https://github.com/lovettchris/wincam/assets/18707114/5159d6d1-df5f-42f4-945b-af40a30ad563)

So it appears python doesn't like big memory copies. We might be able to smooth this a bit by changing the C++ code so it knows how to write directly into a numpy array buffer then the python code doesn't need to do any copy which would also remove work from python garbage collector.

There is also C++ cropping logic that can take some time, for example, I can crop a 1920x1080 game out of a wide 3440x1440 monitor and this gets 12.8ms which is also oddly a bit smoother only ranging from 12-14.  There may be AVX-512 tricks we can to improve the speed of the cropping.

![image](https://github.com/lovettchris/wincam/assets/18707114/9d137cd4-b94d-4850-9f89-02704dcf8939)

There may be some [memcpy optimizations using SSE extensions](https://stackoverflow.com/questions/43343231/enhanced-rep-movsb-for-memcpy) on x64 architectures that we can use to improve the cropping speed.

**Comment by lovettchris** [comment]
note also that dxcam can also be choppy, this is a comparison I just ran on my machine with AMD Ryzen 9 and NVidia 3090 cropping out a 1024x756 image from my primary monitor:

![image](https://github.com/user-attachments/assets/0d813283-46c1-4038-890e-b4948de47325)

**Comment by JuZi233** [comment]
Thank you for your patient reply. I have also noticed the number of cheating frames in dxcam. The time fluctuation is also obvious when videomode= false, and it is very stable when videomode=true, but it seems to be caused by using the previous frame when not getting frames. But dxcam I have tested support for full screen, wincam has not been tested, I will test later. My own package of DX11 screenshots is very stable can do within 2ms full screen screenshots (2560X1440)(dxgi11.dll for python), but doesn't support full screen. any way, wincam is awesome, thanks

**Comment by lovettchris** [comment]
Cool, thanks for the feedback.  Any future suggestions are welcome.

**Comment by lovettchris** [comment]
Cool, thanks for the feedback. Any future suggestions are welcome.

**Comment by eamon-cai** [comment]
When testing latency, using cv2.imshow can lead to inaccurate results due to the display time of cv2, which is roughly influenced by the system sleep precision of about 15ms. At the same time, SIMD operations can be used to accelerate memcpy. I am not very familiar with C++, so I can only implement it simply, and the effect might not be very significant. On my computer, due to the resolution and refresh rate not being high, the performance improvement is not very noticeable, but it can reduce CPU usage. I saw something similar on StackOverflow: https://stackoverflow.com/questions/43343231/enhanced-rep-movsb-for-memcpy.

**Comment by lovettchris** [comment]
Yeah, as I see in that stackoverflow thread I would expect most modern C++ compilers to already optimize the heck out of memcpy, but who knows.  Another possibility is that I might be able to do the cropping in DirectX on the GPU and get faster times that way.

**Comment by eamon-cai** [comment]
Through GPU clipping is feasible. I have seen someone implement it, and it significantly boosts speed. However, I need to implement the shader myself, which is beyond my knowledge. I'm trying it, hahaha.
