### ISSUE TITLE
Failed to start capture

### ISSUE THREAD

**Issue by qq923004243** [lovettchris/wincam#5]
Traceback (most recent call last):
  File "D:\迅雷下载\main\AI-Aimbot-main\testwincap.py", line 9, in <module>
    frame, timestamp = camera.get_bgr_frame()
  File "C:\Users\lixingliang\AppData\Local\Programs\Python\Python310\lib\site-packages\wincam\dxcam.py", line 58, in get_bgr_frame
    raise Exception(f"Failed to start capture, error code {f'{-hr:02x}'}")
Exception: Failed to start capture, error code 01
![2024-08-03_181648](https://github.com/user-attachments/assets/f47c5563-a0bd-4d38-bf92-55b09159e824)

Press ESCAPE to close the window...
Capture failed -2147467262
Error: Failed to start capture, error code 7fffbffe

This is my system environment Win10 2022H 19045.4651, GPU 2070s, but there is indeed no way to start when it is enabled。
```
import cv2
from wincam import DXCamera
x=665
y=550
w=825
h=577
with DXCamera(x, y, w, h, 144) as camera:
    while True:
        frame, timestamp = camera.get_bgr_frame()
        cv2.imshow("frame", frame)
        if cv2.waitKey(1) & 0xFF == 27:
            break
```

**Comment by blaxkwidow** [comment]
try https://github.com/lovettchris/wincam/pull/6

**Comment by qq923004243** [comment]
@blaxkwidow thk u , it is useful .
my code:
```
from wincam import DXCamera
import cv2
import time
x=0
y=0
w=320
h=320
with DXCamera(x, y, w, h, fps=144) as camera:
    frame_count = 0
    start_time = time.time()
    while True:
        frame, timestamp = camera.get_bgr_frame()
        cv2.imshow("frame", frame)
        cv2.waitKey(1)
        frame_count += 1
        elapsed_time = time.time() - start_time

        if elapsed_time > 0:
            fps = frame_count / elapsed_time
            print(f"FPS: {fps:.2f}")
```
